---
- name: Escuta eventos por meio de um webhook
  hosts: localhost

  sources:
    - name: Escuta eventos por meio da porta 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Mostra os eventos que vem chegando
      condition: event.payload.mensagem == "Evento C"
      action:
        print_event:
          pretty: true

    #- name: Executa um Job Template
    #  condition: event.payload.servidor == "db2.lab5.example.com"
    #  action:
    #    run_job_template:
    #      name: RebootMaquina
    #      organization: Default
