---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Mostra os eventos que vem chegando
      #condition: event.payload.mensagem == "Evento B"
      condition: 2 > 1
      action:
        print_event:
          pretty: true
