---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - name: Teste
      #dynatrace.event_driven_ansible.dt_webhook:
      ansible.eda.webhook: 
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Lalá ficou lelé porque lilí deu loló pro lulú
      condition: 2 > 1
      action:
        print_event:
          pretty: true
