---
- name: Escuta eventos por meio de um webhook
  hosts: localhost

  sources:
    - name: Escuta eventos por meio da porta 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Mostra os eventos que vem chegando
      condition: event.payload.mensagem == "Evento C"
      action:
        print_event:
          pretty: true
