---
- name: Rulebook que vigia a AWS
  hosts: all
  sources:
    - ansible.eda.aws_sqs_queue:
        name: eda
        endpoint_url: https://sqs.us-east-2.amazonaws.com/964272839561/eda
        region: us-east-2
        delay_seconds: 10
        access_key: ""
        secret_key: ""
        max_number_of_messages: 1
        
  rules:
    - name: Executa um Job Template
      condition: event.body.Evento == "Mensagem oriunda da fila eda do SQS" and event.body.Origem == "Produção"
      action:
        run_job_template:
          name: Teste com credencial de múltiplos usuários
          organization: Default

