---
- name: Rulebook que vigia eventos do SystemD
  hosts: apache.automation.here
  become: true
  sources:
    - name: asdf
      ansible.eda.journald:
        match: "ALL"

  rules:
    - name: Mostra tudo
      condition: event.journald._comm == 'sudo'
      action:
        print_event:
          pretty: true
          var_root:
            journald.message: journald.message
...
