---
- name: Rulebook que vigia eventos do SystemD
  hosts: apache.automation.here
  sources:
    - name: asdf
      ansible.eda.journald:
        match: "_SYSTEMD_UNIT=sshd.service"

  rules:
    - name: Mostra tudo
      condition: true
      action:
        print_event:
          pretty: true
            #          var_root:
            #            journald.message: journald.message
